#### Data preprocessing with Scikit learn

##### preprocessing Techniques
* It is used to convert raw data into a clean dataset.

#### Data preprocessing steps
* loading the data(reading files)
* Exploring data(summarizing,statistics etc..)
* cleaning data(handling missing data).
* Transforming data(scaling,feature engineering etc..)
  - will learn data preprocessing techniques with sckitlearn,one of the most popular frameworks used for data science
  - Scikit-learn library include tools for data preprocessing and data minig
  - It is imported in python by: import sklearn
  - provides machine learning algorithms: classification,regression,clustering,model validation etc
  - scikitlearn built on numpy,scipy and matplotlib

#### Data imputation(used to deal with missing values)
* It is a method for retaining the mojority of dataset's set and information by substituting missing data with a different value.
* methods 
 - using mean value
 - using median value
 - using mode
 - filling missing values with a constant

In [2]:
from sklearn.impute import SimpleImputer

In [3]:
import pandas as pd
import numpy as np

In [8]:
d1={
    "a":pd.Series([10,89,76,np.nan,56],index=[1,2,3,4,5]),
    "g":pd.Series([454,34,23,34],index=[1,3,4,5]),
    "c":pd.Series([13,45,35,35],index=[1,2,3,4])
}
df=pd.DataFrame(d1)
df

a      g     c
1  10.0  454.0  13.0
2  89.0    NaN  45.0
3  76.0   34.0  35.0
4   NaN   23.0  35.0
5  56.0   34.0   NaN

* fit_transform() from sklearn,preprocessing class is used to preprocessing data for model training

In [9]:
si=SimpleImputer(strategy='median')
si.fit_transform(df)

array([[ 10., 454.,  13.],
       [ 89.,  34.,  45.],
       [ 76.,  34.,  35.],
       [ 66.,  23.,  35.],
       [ 56.,  34.,  35.]])

In [10]:
df.median()

a    66.0
g    34.0
c    35.0
dtype: float64

In [12]:
si=SimpleImputer(strategy='mean')
si.fit_transform(df)

array([[ 10.  , 454.  ,  13.  ],
       [ 89.  , 136.25,  45.  ],
       [ 76.  ,  34.  ,  35.  ],
       [ 57.75,  23.  ,  35.  ],
       [ 56.  ,  34.  ,  32.  ]])

In [13]:
df.mean()

a     57.75
g    136.25
c     32.00
dtype: float64

In [15]:
si=SimpleImputer(strategy='most_frequent')
si.fit_transform(df)

array([[ 10., 454.,  13.],
       [ 89.,  34.,  45.],
       [ 76.,  34.,  35.],
       [ 10.,  23.,  35.],
       [ 56.,  34.,  35.]])

In [16]:
si=SimpleImputer(strategy='constant',fill_value=-1)
si.fit_transform(df)

array([[ 10., 454.,  13.],
       [ 89.,  -1.,  45.],
       [ 76.,  34.,  35.],
       [ -1.,  23.,  35.],
       [ 56.,  34.,  -1.]])

* load titanic dataset
* clean data by using simpleimputer

In [6]:
import pandas as pd
df=pd.read_csv('C:\\Users\\srinadh\\Downloads\\archive (4)\\tested.csv')
df

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [20]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [2]:
from sklearn.impute import SimpleImputer

In [7]:
si=SimpleImputer(strategy='constant',fill_value=-1)
si.fit_transform(df)

array([[892, 0, 3, ..., 7.8292, -1, 'Q'],
       [893, 1, 3, ..., 7.0, -1, 'S'],
       [894, 0, 2, ..., 9.6875, -1, 'Q'],
       ...,
       [1307, 0, 3, ..., 7.25, -1, 'S'],
       [1308, 0, 3, ..., 8.05, -1, 'S'],
       [1309, 0, 3, ..., 22.3583, -1, 'C']], dtype=object)

* [10kg,1000 tons,70 gms,800 gms] --weights
* 10+1000+70+800--- incorrect
* convert into same units-- 'scaling'

* Feature scaling
  * it is atechnique that involves the values of features or variables in a dataset into a similar scale.
- it is the process of normalizing the range of features in a dataset
- real world data often contain features that are varying in degrees of magnitude,range and units
- Therefore inorder for machinelearning models to interpret these features on same scale,we need to perform scaling

* Scaling techniques
  - used to convert raw data into meaningful data
    - standardizing data
    - data range
    - normalizing data
    - robust scaling

* standardizing data(column wise/label wise/feature wise)
  - standard format refers to data that has 0 mean and unit variance(standard deviation=1),the process of converting  data into this format is called data standardization

In [8]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [13]:
df.loc[df['Parch']==0,'Parch']='Zero'
df

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp Parch  \
0                                Kelly, Mr. James    male  34.5      0  Zero   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1  Zero   
2                       Myles, Mr. Thomas Francis    male  62.0      0  Zero   
3                                Wirz, Mr. Albert    male  27.0      0  Zero   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1     1   
..                                            ...     ...   ...    ...   ...   
413                            Spector, Mr. Woolf    male   NaN      0  Zero   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0  Zero   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0  Zero   
416                           Ware, Mr. Frederick    male   NaN      0  Zero   
417                      Peter, Master. Michael J    male   NaN      1     1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [15]:
# to update single column name
df.rename(columns={'Pclass':'PCLASS'},inplace=True)
df

PassengerId  Survived  PCLASS  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp Parch  \
0                                Kelly, Mr. James    male  34.5      0  Zero   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1  Zero   
2                       Myles, Mr. Thomas Francis    male  62.0      0  Zero   
3                                Wirz, Mr. Albert    male  27.0      0  Zero   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1     1   
..                                            ...     ...   ...    ...   ...   
413                            Spector, Mr. Woolf    male   NaN      0  Zero   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0  Zero   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0  Zero   
416                           Ware, Mr. Frederick    male   NaN      0  Zero   
417                      Peter, Master. Michael J    male   NaN      1     1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]