#### numpy 
* numpy stands for numerical python
* it is mainly used to create the n-dimensional arrays
* first we need to import numpy
* how to create numpy array
 - using list,tuple,dict,range and arange functions
* syntax:
 - variable_name=numpy.array(list,tuple,dict)

In [1]:
import numpy as np

In [3]:
print(dir(np))
print(len(dir(np)))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [4]:
# to know the current version?
np.__version__

'1.21.5'

In [2]:
# to create 1d numpy array using list?
import numpy as np
n1=np.array([10,20,30,40,50])
print(n1)
print(type(n1))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [14]:
# to create 2d numpy array using list?
n2=np.array([[1,2,3],[4,5,6.2]])
print(n2)
print(type(n2))

[[1.  2.  3. ]
 [4.  5.  6.2]]
<class 'numpy.ndarray'>


In [15]:
# attributes of numpy array
print(n2)
print(n2.shape)# to get no of rows and columns
print(n2.ndim)# to get the dimensions
print(n1.ndim)
print(n2.size)# to get the no of elements
print(n2.dtype)
print(n2.itemsize)

[[1.  2.  3. ]
 [4.  5.  6.2]]
(2, 3)
2
1
6
float64
8


In [18]:
n1=np.array([1,'python',20.2])
print(n1.itemsize)
print(n1.dtype)

128
<U32


In [11]:

import numpy as np
a=np.arange(10)
c=np.roll(a,2)
print(c)

[8 9 0 1 2 3 4 5 6 7]


In [32]:
# to create  numpy array using tuple?
np.array((10,20,30))

array([10, 20, 30])

In [22]:
# to create  numpy array using dictionary
d1=np.array({'name':'kamal','rlno':203,'course':'CSE'})
print(d1)
print(type(d1))

{'name': 'kamal', 'rlno': 203, 'course': 'CSE'}
<class 'numpy.ndarray'>


In [23]:
# to create  numpy array using range function
n3=np.array(range(10,20))
print(n3)

[10 11 12 13 14 15 16 17 18 19]


In [27]:
n4=np.arange(10,15)
print(n4)

[10 11 12 13 14]


In [28]:
print(np.array(range(1.5,10.5)))

TypeError: 'float' object cannot be interpreted as an integer

In [29]:
print(np.arange(1.5,10.5))
# range is a built in function in python
# arange is a built in function in numpy

[1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]


In [33]:
# linspace
n=np.linspace(1,10)
print(n)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [35]:
n2=np.linspace(10,30,6,dtype=int)
print(n2)# 6 equal parts

[10 14 18 22 26 30]


#### array intialization

In [38]:
# using zeros method to create 1d array
a1=np.zeros(5,dtype=int)
print(a1)

[0 0 0 0 0]


In [39]:
# using zeros method to create 2d array
a1=np.zeros((2,3),dtype=int)
print(a1)

[[0 0 0]
 [0 0 0]]


In [41]:
np.empty((2,4))

array([[0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 9.0710453e-321, 7.5660388e-307, 8.4560344e-307]])

In [49]:
# using ones method
print(np.ones(10))
print(np.ones((10),dtype=int))# to change the float(default) datatype to int

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]


In [60]:
print(np.ones((2,5),dtype=int))# 2d array

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [47]:
print(np.eye((4),dtype=int))# identity matrix

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [5]:
import numpy as np
print(np.identity((3),dtype=int))# identity matrix

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [51]:
print(np.diag([1,2,3,4]))# diagonal matrix

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [52]:
print(np.full(4,7))# to print the one specific

[7 7 7 7]


In [57]:
print(np.full((2,3),5))

[[5 5 5]
 [5 5 5]]


In [66]:
n1=np.array([[1,2],[3,4]])
n2=np.array([[4,2],[5,4]])
print('n1 matrix is:')
print(n1)
print('n2 matrix is:')
print(n2)
print('addition is:',n1+n2)
print('multiplication is:',n1*n2)# element wise product

n1 matrix is:
[[1 2]
 [3 4]]
n2 matrix is:
[[4 2]
 [5 4]]
addition is: [[5 4]
 [8 8]]
multiplication is: [[ 4  4]
 [15 16]]


In [65]:
print('matrix multiplication')
print(n1.dot(n2))

matrix multiplication
[[14 10]
 [32 22]]


##### random()
* it is mainly used to  generate random elements in between range.


In [67]:
rn=np.random
print(dir(rn))

['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'PCG64DXSM', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bounded_integers', '_common', '_generator', '_mt19937', '_pcg64', '_philox', '_pickle', '_sfc64', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'tria

In [70]:
# to generate the single random integer
print(np.random.randint(20,30))

21


In [71]:
# to generate the n no of random integers
print(np.random.randint(20,30,5))

[21 22 21 20 24]


In [72]:
# to generate 2d numpy array using random
print(np.random.randint(10,20,(3,4)))

[[15 15 15 16]
 [17 12 19 14]
 [19 19 17 19]]


In [74]:
print(np.random.randn(4,3))
# -ve random integers from -1

[[ 1.85033499  0.07558992 -0.65297522]
 [ 0.19393348  1.13184684  0.61427833]
 [-1.52497286 -1.56051639 -1.23072379]
 [-0.72209302 -1.07401404 -0.37660152]]


In [75]:
print(np.random.rand(2,3))
# random array of digits from 0

[[0.67708109 0.49263402 0.81840431]
 [0.33901766 0.74429965 0.78832795]]


In [8]:
n=np.array([[1,2],[3,4]])
print(n[0])# to get first row
print(n[-1]) # to get last row
print(n[0,1])# to get specific value
print(n[::-1])# to print reverse numpy array

[1 2]
[3 4]
2
[[3 4]
 [1 2]]


#### boolean indexing and fancy

In [82]:
n=np.random.randint(10,40,(3,4))
print(n)

[[16 17 10 34]
 [13 20 38 25]
 [12 17 24 35]]


In [83]:
print(n<30)

[[ True  True  True False]
 [ True  True False  True]
 [ True  True  True False]]


In [84]:
print(n%2==0)

[[ True False  True  True]
 [False  True  True False]
 [ True False  True False]]


In [85]:
# fancy indexing(to get even values)
print(n[n%2==0])

[16 10 34 20 38 12 24]


##### reshape:
* to convert 1d to 2d array


In [12]:
n1=np.arange(10).reshape(2,5)
print(n1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [90]:
n=np.arange(10)
print(n)
print(np.arange.resize(n,(2,2))

SyntaxError: unexpected EOF while parsing (4282598496.py, line 3)