In [3]:
import numpy as np
np.arange(16).reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

#### stacking
* vstack: to add columns
* hstack: to add rows

In [6]:
a1=np.random.randint(1,10,(2,1))
print(a1)
b1=np.random.randint(1,10,(2,1))
print(b1)
print('vstack')
print(np.vstack((a1,b1)))
print(a1)

[[3]
 [1]]
[[5]
 [2]]
vstack
[[3]
 [1]
 [5]
 [2]]
[[3]
 [1]]


In [12]:
# hstack
a2=np.random.randint(1,10,(2,2))
print(a2)
b2=np.random.randint(1,10,(2,2))
print(b2)
print('hstack')
print(np.hstack((a2,b2)))

[[4 9]
 [3 2]]
[[6 1]
 [3 5]]
hstack
[[4 9 6 1]
 [3 2 3 5]]


#### ravel and flatten methods
* to convert n-d numpy array to one d

In [25]:
# ex on ravel()
a=np.array([[1,2],[3,4]])
print(a)
print('dimensions is:',a.ndim)
b=a.ravel()
print(b)
print(a)

[[1 2]
 [3 4]]
dimensions is: 2
[1 2 3 4]
[[1 2]
 [3 4]]


In [21]:
a=np.random.randint(1,10,(3,4))
print(a)
print('dimensions is:',a.ndim)
b=a.flatten()
print(b)
print(a)

[[3 1 9 3]
 [3 8 2 4]
 [2 5 9 6]]
dimensions is: 2
[3 1 9 3 3 8 2 4 2 5 9 6]
[[3 1 9 3]
 [3 8 2 4]
 [2 5 9 6]]


### pandas
* two types of panda data structure
* series data structure
* dataframe data structure


* how to install and import pandas
 - idle prefer with pip? pip install pandas
 - import libray: import pandas as pd

#### series data structure
* creating series objects using list,tuple,dict and also numpy array.
* create pandas series from array like object using pd.series()
  - syntax: pd.series(list,tuple,dict,numpy_array,indexnames)
  - the no of elements in the index list is always equal to the no of elements in the specified series.
  

In [27]:
import pandas as pd

In [32]:
# creation of series data structure using list
l1=[10,20,33]
sd1=pd.Series(l1)
print(sd1)
print(type(sd1))

0    10
1    20
2    33
dtype: int64
<class 'pandas.core.series.Series'>


In [35]:
# to change index names
sd1.index=['A','B','C']
sd1

A    10
B    20
C    33
dtype: int64

In [40]:
sd2=pd.Series([10,'ldjf',12.3,565,'kal'],index=['A','B','C','D','E'])
print(sd2)

A      10
B    ldjf
C    12.3
D     565
E     kal
dtype: object


In [41]:
np1=np.array([10,2,3])
s2=pd.Series(np1)
print(s2)

0    10
1     2
2     3
dtype: int32


In [42]:
# creation of series using dict
d1={'name':'jass','rlno':25,'course':'CSE'}
s3=pd.Series(d1)
print(s3)

name      jass
rlno        25
course     CSE
dtype: object


In [44]:
# creation of series using tuple
s4=pd.Series((10,2,3))
print(s4)

0    10
1     2
2     3
dtype: int64


#### series indexing
* to get the data 
* to access the values from a series using indexes

In [46]:
s2=pd.Series([10,20,30,'prht',12.5])
print(s2)

0      10
1      20
2      30
3    prht
4    12.5
dtype: object


In [47]:
# to access the value from a series
s2[3]

'prht'

In [49]:
s2[::2]# to get alternative rows

0      10
2      30
4    12.5
dtype: object

In [50]:
s2[:3]

0    10
1    20
2    30
dtype: object

In [51]:
print(s2[::-1])

4    12.5
3    prht
2      30
1      20
0      10
dtype: object
